"""Tick-based simulation engine with live, historical, and demo modes."""

from __future__ import annotations

import argparse
import csv
import random
import time
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

from config.settings import get_settings
from database.db import create_session_factory, init_db
from database.repository import TelemetryRepository
from app.pipeline import AquaSensePipeline
from schemas.telemetry import SensorReading
from simulator.facility_topology import (
    FacilityTopology,
    ZoneDefinition,
    available_presets,
    build_facility_topology,
)

from .fault_injector import FaultInjector
from .occupancy_model import OccupancyModel
from .sensor_emulator import SensorEmulator


# ============================================================
# RESULT SCHEMAS
# ============================================================


@dataclass
class TickResult:
    """Result generated by one simulator tick."""

    timestamp: datetime
    readings: list[SensorReading]
    occupancy_by_zone: dict[str, int]


@dataclass
class HistoricalGenerationSummary:
    """Summary returned after historical data generation."""

    total_readings: int
    sample_readings: list[SensorReading]
    database_path: Path
    sample_csv_path: Path


# ============================================================
# SIMULATION ENGINE
# ============================================================


class SimulationEngine:
    """
    Coordinate topology, occupancy, faults, telemetry,
    AquaSense processing, and persistence.

    The simulator is deterministic when a fixed seed is used.
    """

    def __init__(
        self,
        preset_name: str,
        database_path: Path | None = None,
        start_time: datetime | None = None,
        tick_minutes: int = 1,
        live_tick_seconds: float = 1.0,
        seed: int = 42,
    ) -> None:

        if tick_minutes <= 0:
            raise ValueError(
                "tick_minutes must be positive"
            )

        if live_tick_seconds < 0:
            raise ValueError(
                "live_tick_seconds cannot be negative"
            )

        settings = get_settings()

        self.database_path = (
            database_path
            or settings.database_path
        )

        self.topology: FacilityTopology = (
            build_facility_topology(
                preset_name
            )
        )

        self.tick_minutes = tick_minutes
        self.live_tick_seconds = live_tick_seconds

        self.current_time = (
            start_time
            or datetime(
                2026,
                1,
                5,
                6,
                0,
                tzinfo=timezone.utc,
            )
        )

        self._rng = random.Random(seed)

        # --------------------------------------------------------
        # Simulation components
        # --------------------------------------------------------

        self.occupancy_model = OccupancyModel()

        self.sensor_emulator = SensorEmulator()

        self.fault_injector = FaultInjector()

        # --------------------------------------------------------
        # Database
        # --------------------------------------------------------

        init_db(self.database_path)

        self.repository = TelemetryRepository(
            create_session_factory(
                self.database_path
            )
        )

        self.repository.register_topology(
            self.topology
        )

        # --------------------------------------------------------
        # AquaSense AI processing pipeline
        # --------------------------------------------------------

        self.pipeline = AquaSensePipeline()

        self._running = False

    # ============================================================
    # ENGINE CONTROL
    # ============================================================

    def start(self) -> None:
        """Start the simulator."""

        self._running = True

    def stop(self) -> None:
        """Stop the simulator."""

        self._running = False

    @property
    def running(self) -> bool:
        """Return whether the simulator is currently running."""

        return self._running

    # ============================================================
    # FAULT INJECTION
    # ============================================================

    def inject_fault(
        self,
        fault_type: str,
        duration_minutes: int,
        severity: str,
        **targets: str,
    ) -> None:
        """
        Add a fault beginning at the current simulated time.

        Supported target keywords:

            fixture_id
            sensor_id
            zone_id
        """

        self.fault_injector.inject_fault(
            fault_type=fault_type,
            duration_minutes=duration_minutes,
            severity=severity,
            start_time=self.current_time,
            fixture_id=targets.get(
                "fixture_id"
            ),
            sensor_id=targets.get(
                "sensor_id"
            ),
            zone_id=targets.get(
                "zone_id"
            ),
        )

    def get_active_faults(self):
        """Return faults active at the current simulation time."""

        return self.fault_injector.get_active_faults(
            self.current_time
        )

    def get_scheduled_faults(self):
        """Return every scheduled fault."""

        return self.fault_injector.list_faults()

    # ============================================================
    # SINGLE TICK
    # ============================================================

    def run_tick(
        self,
        persist: bool = True,
    ) -> TickResult:
        """
        Generate telemetry for one simulation tick.

        Flow:

            Occupancy
                ↓
            Fault Injection
                ↓
            Sensor Emulator
                ↓
            Database
                ↓
            AquaSense Pipeline
                ↓
            Maintenance Ticket
        """

        active_faults = (
            self.fault_injector.get_active_faults(
                self.current_time
            )
        )

        # --------------------------------------------------------
        # Occupancy
        # --------------------------------------------------------

        occupancy_by_zone = {
            zone.zone_id: self._zone_occupancy(
                zone,
                active_faults,
            )
            for zone in self.topology.zones
        }

        # --------------------------------------------------------
        # Telemetry generation
        # --------------------------------------------------------

        readings = (
            self.sensor_emulator.generate_tick_readings(
                timestamp=self.current_time,
                topology=self.topology,
                occupancy_by_zone=occupancy_by_zone,
                active_faults=active_faults,
                rng=self._rng,
            )
        )

        # --------------------------------------------------------
        # Persistence + AI pipeline
        # --------------------------------------------------------

        if persist:

            # 1. Save raw telemetry
            self.repository.save_sensor_readings(
                readings
            )

            # 2. Process every reading
            for reading in readings:

                pipeline_result = (
                    self.pipeline.process_reading(
                        reading
                    )
                )

                # 3. Persist generated maintenance ticket
                if (
                    pipeline_result.maintenance_ticket
                    is not None
                ):
                    self.repository.save_maintenance_ticket(
                        pipeline_result.maintenance_ticket
                    )

        # --------------------------------------------------------
        # Build result
        # --------------------------------------------------------

        result = TickResult(
            timestamp=self.current_time,
            readings=readings,
            occupancy_by_zone=occupancy_by_zone,
        )

        # Advance simulation clock
        self.current_time += timedelta(
            minutes=self.tick_minutes
        )

        return result

    # ============================================================
    # LIVE MODE
    # ============================================================

    def run_live(
        self,
        ticks: int | None = None,
    ) -> list[TickResult]:
        """
        Run the simulator in live mode.

        If ticks is None, the simulator continues until stop()
        is called.
        """

        self.start()

        results: list[TickResult] = []

        iterations = 0

        while self._running:

            results.append(
                self.run_tick()
            )

            iterations += 1

            if (
                ticks is not None
                and iterations >= ticks
            ):
                self.stop()
                break

            if self.live_tick_seconds > 0:
                time.sleep(
                    self.live_tick_seconds
                )

        return results

    # ============================================================
    # HISTORICAL MODE
    # ============================================================

    def run_historical(
        self,
        duration: timedelta,
        persist: bool = True,
    ) -> list[TickResult]:
        """
        Generate historical telemetry without real-time delays.
        """

        if duration.total_seconds() <= 0:
            raise ValueError(
                "duration must be positive"
            )

        total_minutes = int(
            duration.total_seconds()
            // 60
        )

        steps = (
            total_minutes
            // self.tick_minutes
        )

        return [
            self.run_tick(
                persist=persist
            )
            for _ in range(steps)
        ]

    # ============================================================
    # DEMO MODE
    # ============================================================

    def run_demo(
        self,
        ticks: int = 15,
        fault_type: str = "continuous_leak",
        fault_duration_minutes: int = 15,
        severity: str = "high",
    ) -> list[TickResult]:
        """
        Run a controlled demonstration.

        The demo:

        1. Generates healthy telemetry.
        2. Selects a real fixture.
        3. Injects a fault into that fixture.
        4. Continues simulation.
        5. Allows the AquaSense pipeline to detect it.
        6. Persists telemetry and maintenance decisions.

        This mode is intended for presentations and testing.
        """

        if ticks <= 0:
            raise ValueError(
                "ticks must be positive"
            )

        if fault_duration_minutes <= 0:
            raise ValueError(
                "fault_duration_minutes must be positive"
            )

        results: list[TickResult] = []

        # --------------------------------------------------------
        # Generate a healthy starting tick
        # --------------------------------------------------------

        healthy_tick = self.run_tick(
            persist=True
        )

        results.append(
            healthy_tick
        )

        if not healthy_tick.readings:
            return results

        # --------------------------------------------------------
        # Pick a real fixture
        # --------------------------------------------------------

        target_fixture_id = (
            healthy_tick.readings[0].fixture_id
        )

        # --------------------------------------------------------
        # Inject demonstration fault
        # --------------------------------------------------------

        self.inject_fault(
            fault_type=fault_type,
            duration_minutes=fault_duration_minutes,
            severity=severity,
            fixture_id=target_fixture_id,
        )

        # --------------------------------------------------------
        # Continue simulation
        # --------------------------------------------------------

        remaining_ticks = max(
            0,
            ticks - 1,
        )

        for _ in range(
            remaining_ticks
        ):
            results.append(
                self.run_tick(
                    persist=True
                )
            )

        return results

    # ============================================================
    # OCCUPANCY
    # ============================================================

    def _zone_occupancy(
        self,
        zone: ZoneDefinition,
        active_faults,
    ) -> int:
        """
        Generate occupancy for a zone.

        Occupancy spikes can temporarily increase the
        generated occupancy when a corresponding fault
        is active.
        """

        occupancy = (
            self.occupancy_model.get_expected_occupancy(
                timestamp=self.current_time,
                facility_type=(
                    self.topology.facility.facility_type
                ),
                zone_type=zone.zone_type,
                zone_capacity=zone.capacity,
                rng=self._rng,
            )
        )

        # --------------------------------------------------------
        # Occupancy spike fault
        # --------------------------------------------------------

        for fault in active_faults:

            if fault.fault_type != "occupancy_spike":
                continue

            if (
                fault.zone_id is not None
                and fault.zone_id != zone.zone_id
            ):
                continue

            if (
                fault.fixture_id is not None
            ):
                continue

            multiplier = (
                fault.severity_factor
            )

            occupancy = int(
                round(
                    occupancy * multiplier
                )
            )

        # --------------------------------------------------------
        # Respect zone capacity
        # --------------------------------------------------------

        occupancy = max(
            0,
            min(
                occupancy,
                zone.capacity,
            ),
        )

        return occupancy


# ============================================================
# HISTORICAL DATA GENERATOR
# ============================================================


def generate_default_historical_data(
    database_path: Path,
    sample_csv_path: Path,
    days: int = 7,
    seed: int = 42,
) -> HistoricalGenerationSummary:
    """
    Generate historical telemetry and save a CSV sample.
    """

    if days <= 0:
        raise ValueError(
            "days must be positive"
        )

    engine = SimulationEngine(
        preset_name="airport",
        database_path=database_path,
        start_time=datetime(
            2026,
            1,
            1,
            0,
            0,
            tzinfo=timezone.utc,
        ),
        tick_minutes=1,
        live_tick_seconds=0,
        seed=seed,
    )

    total_minutes = days * 24 * 60

    results = []

    for _ in range(
        total_minutes
    ):
        results.append(
            engine.run_tick(
                persist=True
            )
        )

    # ------------------------------------------------------------
    # Flatten readings
    # ------------------------------------------------------------

    all_readings: list[
        SensorReading
    ] = []

    for result in results:
        all_readings.extend(
            result.readings
        )

    # ------------------------------------------------------------
    # Write CSV
    # ------------------------------------------------------------

    sample_csv_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with sample_csv_path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=[
                "sensor_id",
                "fixture_id",
                "zone_id",
                "facility_id",
                "timestamp",
                "sensor_type",
                "value",
                "unit",
                "diagnostic_status",
                "quality_flag",
                "metadata",
            ],
        )

        writer.writeheader()

        for reading in all_readings:

            writer.writerow(
                {
                    "sensor_id": (
                        reading.sensor_id
                    ),
                    "fixture_id": (
                        reading.fixture_id
                    ),
                    "zone_id": (
                        reading.zone_id
                    ),
                    "facility_id": (
                        reading.facility_id
                    ),
                    "timestamp": (
                        reading.timestamp.isoformat()
                    ),
                    "sensor_type": (
                        reading.sensor_type
                    ),
                    "value": (
                        reading.value
                    ),
                    "unit": (
                        reading.unit
                    ),
                    "diagnostic_status": (
                        reading.diagnostic_status
                    ),
                    "quality_flag": (
                        reading.quality_flag
                    ),
                    "metadata": (
                        reading.metadata
                    ),
                }
            )

    return HistoricalGenerationSummary(
        total_readings=len(
            all_readings
        ),
        sample_readings=all_readings[
            :10
        ],
        database_path=database_path,
        sample_csv_path=sample_csv_path,
    )


# ============================================================
# CLI
# ============================================================


def _build_cli_parser() -> argparse.ArgumentParser:
    """Build command-line interface."""

    parser = argparse.ArgumentParser(
        description=(
            "AquaSense AI Phase 1 simulator"
        )
    )

    subparsers = (
        parser.add_subparsers(
            dest="command",
            required=True,
        )
    )

    # --------------------------------------------------------
    # HISTORICAL
    # --------------------------------------------------------

    historical = subparsers.add_parser(
        "historical",
        help="Generate historical telemetry",
    )

    historical.add_argument(
        "--days",
        type=int,
        default=7,
    )

    historical.add_argument(
        "--seed",
        type=int,
        default=42,
    )

    # --------------------------------------------------------
    # LIVE
    # --------------------------------------------------------

    live = subparsers.add_parser(
        "live",
        help="Run live telemetry simulation",
    )

    live.add_argument(
        "--facility",
        choices=available_presets(),
        default="airport",
    )

    live.add_argument(
        "--ticks",
        type=int,
        default=5,
    )

    live.add_argument(
        "--seed",
        type=int,
        default=42,
    )

    # --------------------------------------------------------
    # DEMO
    # --------------------------------------------------------

    demo = subparsers.add_parser(
        "demo",
        help="Run AquaSense demonstration mode",
    )

    demo.add_argument(
        "--facility",
        choices=available_presets(),
        default="airport",
    )

    demo.add_argument(
        "--ticks",
        type=int,
        default=15,
    )

    demo.add_argument(
        "--fault",
        choices=[
            "continuous_leak",
            "ghost_flush",
            "sensor_dropout",
            "occupancy_spike",
            "abnormal_flow",
        ],
        default="continuous_leak",
    )

    demo.add_argument(
        "--duration",
        type=int,
        default=15,
    )

    demo.add_argument(
        "--severity",
        choices=[
            "low",
            "medium",
            "high",
        ],
        default="high",
    )

    demo.add_argument(
        "--seed",
        type=int,
        default=42,
    )

    return parser


# ============================================================
# CLI MAIN
# ============================================================


def main() -> None:
    """CLI entry point."""

    parser = _build_cli_parser()

    args = parser.parse_args()

    settings = get_settings()

    # ========================================================
    # HISTORICAL
    # ========================================================

    if args.command == "historical":

        summary = (
            generate_default_historical_data(
                database_path=(
                    settings.database_path
                ),
                sample_csv_path=(
                    settings.sample_csv_path
                ),
                days=args.days,
                seed=args.seed,
            )
        )

        print(
            f"Generated "
            f"{summary.total_readings} readings "
            f"into "
            f"{summary.database_path} "
            f"and "
            f"{summary.sample_csv_path}"
        )

        return

    # ========================================================
    # DEMO
    # ========================================================

    if args.command == "demo":

        engine = SimulationEngine(
            preset_name=args.facility,
            database_path=(
                settings.database_path
            ),
            start_time=datetime(
                2026,
                1,
                5,
                6,
                0,
                tzinfo=timezone.utc,
            ),
            tick_minutes=1,
            live_tick_seconds=0,
            seed=args.seed,
        )

        print(
            "================================================"
        )
        print(
            "AquaSense AI DEMO MODE"
        )
        print(
            "================================================"
        )

        print(
            f"Facility : {args.facility}"
        )

        print(
            f"Fault    : {args.fault}"
        )

        print(
            f"Severity : {args.severity}"
        )

        print(
            f"Duration : {args.duration} minutes"
        )

        print(
            "================================================"
        )

        results = engine.run_demo(
            ticks=args.ticks,
            fault_type=args.fault,
            fault_duration_minutes=args.duration,
            severity=args.severity,
        )

        for result in results:

            active_faults = (
                engine.fault_injector
                .get_active_faults(
                    result.timestamp
                )
            )

            print(
                f"{result.timestamp.isoformat()} "
                f"occupancy="
                f"{sum(result.occupancy_by_zone.values())} "
                f"readings="
                f"{len(result.readings)} "
                f"active_faults="
                f"{len(active_faults)}"
            )

        print(
            "================================================"
        )

        print(
            "Demo completed."
        )

        return

    # ========================================================
    # LIVE
    # ========================================================

    engine = SimulationEngine(
        preset_name=args.facility,
        database_path=(
            settings.database_path
        ),
        start_time=datetime(
            2026,
            1,
            5,
            6,
            0,
            tzinfo=timezone.utc,
        ),
        tick_minutes=1,
        live_tick_seconds=(
            settings.live_tick_seconds
        ),
        seed=args.seed,
    )

    results = engine.run_live(
        ticks=args.ticks
    )

    for result in results:

        print(
            f"{result.timestamp.isoformat()} "
            f"occupancy="
            f"{sum(result.occupancy_by_zone.values())} "
            f"readings="
            f"{len(result.readings)}"
        )


# ============================================================
# MODULE ENTRY POINT
# ============================================================


if __name__ == "__main__":
    main()